### ISSUE TITLE
mode.py error

### ISSUE THREAD

**Issue by thekingofkings** [kkspeed/chess#2]
Direct compile the AC learning model in model.py. Encounter the following error message:

> ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv2d_1/convolution' (op: 'Conv2D') with input shapes: [?,10,9,1], [3,3,10,32].

However, the training process is OK.

**Comment by kkspeed** [comment]
__main__ in model.py was out of sync. padding should not be added as it will make models generated by train.py inconsistent.
